### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by harr1193** [harr1193/MI-449-SS17-741-js-conditionals-uMDt4P#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://harr1193.github.io/MI-449-SS17-741-js-conditionals-uMDt4P/) and meets the following criteria:

- [x] Use the `prompt` and `confirm` functions (each at least once) to collect choices from the user (the entire story will take place in dialog boxes, so your `body` element could actually be empty, apart from the `script` element to include your JavaScript)
- [x] Use `if`, `else if`, and `else` to branch the story, based on user choices
- [x] In at least one branch, there should be at least 3 choices for the user to make
- [x] Include at least one branch where different things can happen each time with `Math.random()`
- [x] Use a logical operator (`&&` or `||`) at least once, where it makes sense
- [x] It should be impossible for an error to ever occur when playing your game, including handling for `null`/`undefined` where appropriate
- [x] All string input should be normalized, so that extra whitespace or a letter that's the wrong case will never cause a failed match
- [x] At least one number value is collected and used in a comparison (don't forget to convert it into a number first)
- [x] Don't get _too_ carried away -- it can be tempting to build a complex video game, but remember, you can always come back and build on this project later

**Comment by stuartpearman** [comment]
Hey Kyle, nice work and cool idea. What's behind door number 3 though?? Add something in for that and you'll be all set :+1:

**Comment by harr1193** [comment]
Added an option for door 3

**Comment by stuartpearman** [comment]
Hey Kyle,

I see the change you made, but it's in the wrong branch. You've put the new message under door number two. It will only pop up if you don't make the Joker turn off the machine. You'll want to create a new `else if` branch after the door number 2 else if branch.

You'll also probably want to create an else branch for if the player doesn't choose 1, 2, or 3.

**Comment by harr1193** [comment]
Corrected the door 3 branch, and added an else if 1, 2 or 3 is not chosen

**Comment by stuartpearman** [comment]
Much better, nice job Kyle! :shipit:
